name: frontend-stack

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_WINDMILL_URL: https://windmill.mdsoluciones.ar
        VITE_AUTH_MODE: mock
        VITE_WINDMILL_WORKSPACE: arba
    ports:
      - "3011:80"
    restart: unless-stopped
    networks:
      - iibb-network

networks:
  iibb-network:
    external: true
