name: surveyjs

services:
  frontend-surveyjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        NEXT_PUBLIC_WINDMILL_URL: http://localhost
        NEXT_PUBLIC_AUTH_MODE: mock
        NEXT_PUBLIC_WINDMILL_WORKSPACE: formulario
    ports:
      - "3014:3000"
    restart: unless-stopped
    # networks:
    #   - iibb-network

# networks:
#   iibb-network:
#     external: true
