services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    volumes:
      - .:/app
      - /app/node_modules
    # env_file: .env.example
    environment:
      - VITE_WINDMILL_URL=http://localhost
      - VITE_AUTH_MODE=mock
      - VITE_WINDMILL_WORKSPACE=arba
      - VITE_FORMIO_URL=http://localhost:3010
    restart: unless-stopped

