name: apis
services:
  mockoon:
    image: mockoon/cli:latest
    command: ["--data", "/data/iibb.json", "--port", "3001", "--hostname", "0.0.0.0"]
    ports:
      - "3001:3001"
    volumes:
      - ./iibb.json:/data/iibb.json:ro
    restart: unless-stopped