summary: ''
description: ''
lock: '!inline f/config/get_user_config.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    token:
      type: string
      description: ''
      default: null
      originalType: string
  required:
    - token
